#!/usr/bin/env bash

# grep for string from list

StringVal="ACCOUNT_PAID_OFF  ADDRESS_CHANGED  AUTO_ACH_PAYMENT_APPLIED  DEVOPS  MED_ACH_MICROPAYMENT_FAILED  MED_ACH_PAYMENT_FAILED  MED_ACH_TRANSFER_FAILED  MED_ADJUSTMENT_MADE  MED_BALANCE_TRANSFER  MED_BANK_ACCOUNT_VERIFIED  MED_CONTACT_US  MED_EMAIL_CHANGED  MED_EMAIL_SECURITY_CODE  MED_EMAIL_VERIFICATION  MED_ENROLLMENT_REMINDER  MED_EXTERNAL_WRAPPER_LEFT  MED_FORGOT_PASSWORD  MED_INTERNAL_WRAPPER  MED_INTRODUCTION  MED_LOST_REPLACE  MED_MOBILE_CHANGED  MED_MOBILE_SECURITY_CODE  MED_NEW_BANK_ACCOUNT  MED_NEW_ECARD_TRANSFER  MED_NEW_USER  MED_OFFER  MED_OFFER_CANCELED  MED_OFFER_EXPIRED  MED_PASSWORD_CHANGED  MED_PAYMENT_DUE  MED_PAYMENT_MADE  MED_PIN_CHANGED  MED_PORTAL_INVITATION  MED_SECURITY_CODE_EMAIL  MED_STATEMENT_AVAILABLE  MED_TRANSFER_FAILED  MED_TRANSFER_MADE  MED_USER_DOCUMENT  MED_USER_LOCKED  MED_WELCOME  PAYROLL_DEDUCTION_APPLIED  SORTIS_EXTERNAL_WRAPPER_LEFT  SORTIS_MEDZERO_EXTERNAL_WRAPPER_LEFT"

# Iterate the string variable using for loop
for val in $StringVal; do
    echo $val
    grep -i -n -r -I --include=*.java --include=*.ts --include=*.js $val > ~/temp.txt
    mv ~/temp.txt grep-${val,,}.txt
done
